using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using TablaPeriodica.Models;

namespace TablaPeriodica
{
    public partial class Cuestionario : Form
    {
        #region elementos
        //public Question QHidrogeno;
        //public Question QLitio;
        //public Question QSodio;
        //public Question QPotasio;
        //public Question QRubidio;
        //public Question QCesio;
        //public Question QFrancio;
        //public Question QBerilio;
        //public Question QMagnesio;
        //public Question QCalcio;
        //public Question QEstroncio;
        //public Question QBario;
        //public Question QRadio;
        //public Question QEscandio;
        //public Question QItrio;
        //public Question QLantanidos;
        //public Question QActinidos;
        //public Question QTitanio;
        //public Question QCirconio;
        //public Question QHafnio;
        //public Question QRutherfordio;
        //public Question QLantano;
        //public Question QActinio;
        //public Question QVanadio;
        //public Question QNiobio;
        //public Question QTantalo;
        //public Question QDubnio;
        //public Question QCerio;
        //public Question QTorio;
        //public Question QCromo;
        //public Question QMolibdeno;
        //public Question QWolframio;
        //public Question QSeaborgio;
        //public Question QPraseodimio;
        //public Question QProtactinio;
        //public Question QManganesio;
        //public Question QTecnecio;
        //public Question QRenio;
        //public Question QBohrio;
        //public Question QNeodimio;
        //public Question QUranio;
        //public Question QHierro;
        //public Question QRutenio;
        //public Question QOsmio;
        //public Question QHasio;
        //public Question QPrometio;
        //public Question QNeptunio;
        //public Question QCobalto;
        //public Question QRodio;
        //public Question QIridio;
        //public Question QMeitnerio;
        //public Question QSamario;
        //public Question QPlutonio;
        //public Question QNiquel;
        //public Question QPaladio;
        //public Question QPlatino;
        //public Question QDarmstatio;
        //public Question QEuropio;
        //public Question QAmericio;
        //public Question QCobre;
        //public Question QPlata;
        //public Question QOro;
        //public Question QRoentgenio;
        //public Question QGadolinio;
        //public Question QCurio;
        //public Question QZinc;
        //public Question QCadmio;
        //public Question QMercurio;
        //public Question QCopernicio;
        //public Question QTerbio;
        //public Question QBerkelio;
        //public Question QBoro;
        //public Question QAluminio;
        //public Question QGalio;
        //public Question QIndio;
        //public Question QTalio;
        //public Question QNihonio;
        //public Question QDisprosio;
        //public Question QCalifornio;
        //public Question QCarbono;
        //public Question QSilicio;
        //public Question QGermanio;
        //public Question QEstaño;
        //public Question QPlomo;
        //public Question QFlerovio;
        //public Question QHolmio;
        //public Question QEinstenio;
        //public Question QNitrogeno;
        //public Question QFosforo;
        //public Question QArsenico;
        //public Question QAntimonio;
        //public Question QBismuto;
        //public Question QMoscovio;
        //public Question QErbio;
        //public Question QFermio;
        //public Question QOxigeno;
        //public Question QAzufre;
        //public Question QSelenio;
        //public Question QTelurio;
        //public Question QPolonio;
        //public Question QLivermorio;
        //public Question QTulio;
        //public Question QMendelevio;
        //public Question QFluor;
        //public Question QCloro;
        //public Question QBromo;
        //public Question QYodo;
        //public Question QAstato;
        //public Question QTeneso;
        //public Question QIterbio;
        //public Question QNobelio;
        //public Question QHelio;
        //public Question QNeon;
        //public Question QArgon;
        //public Question QKripton;
        //public Question QXenon;
        //public Question QRadon;
        //public Question QOganeson;
        //public Question QLutecio;
        //public Question QLawrencio;
        #endregion
        public Question QotrosNoMetales;
        public Question QAlcalinos;
        public Question QAlcalinoterreo;
        public Question QMetalesTransicion;
        public Question QOtrosMetales;
        public Question QLantanidos;
        public Question QActinidos;
        public Question QMetaloide;
        public Question QHalogenos;
        public Question QGasesNobles;

        public string Elemento;
        public bool respuesta = false;
        public Cuestionario(string elemento)
        {
            Respuesta.respuesta = false;
            Elemento = elemento;
            InitializeComponent();
            crearPreguntas();
            llenarCuestionario(elemento);
        }

        public void llenarCuestionario(string elemento)
        {
            switch (elemento)
            {
                case "OtrosNoMetales": this.textBox1.Text = QotrosNoMetales.Pregunta; this.radioButton1.Text = QotrosNoMetales.Respuesta; this.radioButton2.Text = "Papaya"; this.radioButton3.Text = "Alcalinos"; this.radioButton4.Text = "Circuitos"; break;
                case "Alcalinos": this.textBox1.Text = QAlcalinos.Pregunta; this.radioButton3.Text = QAlcalinos.Respuesta; this.radioButton2.Text = "Otros No Metales"; this.radioButton1.Text = "Gases Nobles"; this.radioButton4.Text = "Relampagos"; break;
                case "Alcalinoterreo": this.textBox1.Text = QAlcalinoterreo.Pregunta; this.radioButton3.Text = QAlcalinoterreo.Respuesta; this.radioButton4.Text = "Adamantium"; this.radioButton1.Text = "Gases Nobles"; this.radioButton2.Text = "Trozo de Pan"; break;
                case "MetalesTransicion": this.textBox1.Text = QMetalesTransicion.Pregunta; this.radioButton2.Text = QMetalesTransicion.Respuesta; this.radioButton4.Text = "Plato de Cereal"; this.radioButton1.Text = "Gases Nobles"; this.radioButton3.Text = "Alcalinos"; break;
                case "OtrosMetales": this.textBox1.Text = QOtrosMetales.Pregunta; this.radioButton3.Text = QOtrosMetales.Respuesta; this.radioButton4.Text = "Nubes"; this.radioButton1.Text = "Vibranium"; this.radioButton2.Text = "Otros No Metales"; break;
                case "Lantanidos": this.textBox1.Text = QLantanidos.Pregunta; this.radioButton4.Text = QLantanidos.Respuesta; this.radioButton3.Text = "Sol"; this.radioButton1.Text = "Plastico"; this.radioButton2.Text = "Metales de Transicion"; break;
                case "Actinidos": this.textBox1.Text = QActinidos.Pregunta; this.radioButton1.Text = QActinidos.Respuesta; this.radioButton3.Text = "Luz"; this.radioButton4.Text = "Gelatina"; this.radioButton2.Text = "Alcalinos"; break;
                case "Metaloide": this.textBox1.Text = QMetaloide.Pregunta; this.radioButton2.Text = QMetaloide.Respuesta; this.radioButton3.Text = "Magma"; this.radioButton4.Text = "Otros No Metales"; this.radioButton1.Text = "Actinidos"; break;
                case "Halogenos": this.textBox1.Text = QHalogenos.Pregunta; this.radioButton4.Text = QHalogenos.Respuesta; this.radioButton3.Text = "Metaloides"; this.radioButton2.Text = "Arena"; this.radioButton1.Text = "Pigmentos"; break;
                case "GasesNobles": this.textBox1.Text = QGasesNobles.Pregunta; this.radioButton1.Text = QGasesNobles.Respuesta; this.radioButton3.Text = "Otros No Metales"; this.radioButton2.Text = "Diamantes"; this.radioButton4.Text = "Otros Metales"; break;
                    #region elementos
                    //case "btnHidrogeno": this.textBox1.Text = QHidrogeno.Pregunta; this.radioButton1.Text = QHidrogeno.Respuesta; this.radioButton2.Text = "Oxigeno"; this.radioButton3.Text = "Cesio"; this.radioButton4.Text = "Bario"; break;
                    //case "btnLitio": this.textBox1.Text = QLitio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QLitio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnSodio": this.textBox1.Text = QSodio.Pregunta; this.radioButton1.Text = QSodio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnPotasio": this.textBox1.Text = QPotasio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QPotasio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnRubidio": this.textBox1.Text = QRubidio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QRubidio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnCesio": this.textBox1.Text = QCesio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QCesio.Respuesta; break;
                    //case "btnFrancio": this.textBox1.Text = QFrancio.Pregunta; this.radioButton1.Text = QFrancio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnBerilio": this.textBox1.Text = QBerilio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QBerilio.Respuesta; break;
                    //case "btnMagnesio": this.textBox1.Text = QMagnesio.Pregunta; this.radioButton1.Text = QMagnesio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnCalcio": this.textBox1.Text = QCalcio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QCalcio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnEstroncio": this.textBox1.Text = QEstroncio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QEstroncio.Respuesta; break;
                    //case "btnBario": this.textBox1.Text = QBario.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QBario.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnRadio": this.textBox1.Text = QRadio.Pregunta; this.radioButton1.Text = QRadio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnEscandio": this.textBox1.Text = QEscandio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QEscandio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnItrio": this.textBox1.Text = QItrio.Pregunta; this.radioButton1.Text = QItrio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnLantanidos": this.textBox1.Text = QLantanidos.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QLantanidos.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnActinidos": this.textBox1.Text = QActinidos.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QActinidos.Respuesta; break;
                    //case "btnTitanio": this.textBox1.Text = QTitanio.Pregunta; this.radioButton1.Text = QTitanio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnCirconio": this.textBox1.Text = QCirconio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QCirconio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnHafnio": this.textBox1.Text = QHafnio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QHafnio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnRutherfordio": this.textBox1.Text = QRutherfordio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QRutherfordio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnLantano": this.textBox1.Text = QLantano.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QLantano.Respuesta; break;
                    //case "btnActinio": this.textBox1.Text = QActinio.Pregunta; this.radioButton1.Text = QActinio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnVanadio": this.textBox1.Text = QVanadio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QVanadio.Respuesta; break;
                    //case "btnNiobio": this.textBox1.Text = QNiobio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QNiobio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnTantalo": this.textBox1.Text = QTantalo.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QTantalo.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnDubnio": this.textBox1.Text = QDubnio.Pregunta; this.radioButton1.Text = QDubnio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnCerio": this.textBox1.Text = QCerio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QCerio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnTorio": this.textBox1.Text = QTorio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QTorio.Respuesta; break;
                    //case "btnCromo": this.textBox1.Text = QCromo.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QCromo.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnMolibdeno": this.textBox1.Text = QMolibdeno.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QMolibdeno.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnWolframio": this.textBox1.Text = QWolframio.Pregunta; this.radioButton1.Text = QWolframio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnSeaborgio": this.textBox1.Text = QSeaborgio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QSeaborgio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnPraseodimio": this.textBox1.Text = QPraseodimio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QPraseodimio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnProtactinio": this.textBox1.Text = QProtactinio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QProtactinio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnManganesio": this.textBox1.Text = QManganesio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QManganesio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnTecnecio": this.textBox1.Text = QTecnecio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QTecnecio.Respuesta; break;
                    //case "btnRenio": this.textBox1.Text = QRenio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QRenio.Respuesta; break;
                    //case "btnBohrio": this.textBox1.Text = QBohrio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QBohrio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnNeodimio": this.textBox1.Text = QNeodimio.Pregunta; this.radioButton1.Text = QNeodimio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnUranio": this.textBox1.Text = QUranio.Pregunta; this.radioButton1.Text = QUranio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnHierro": this.textBox1.Text = QHierro.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QHierro.Respuesta; break;
                    //case "btnRutenio": this.textBox1.Text = QRutenio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QRutenio.Respuesta; break;
                    //case "btnOsmio": this.textBox1.Text = QOsmio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QOsmio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnHasio": this.textBox1.Text = QHasio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QHasio.Respuesta; this.radioButton3.Text = "      "; this.radioButton4.Text = "      "; break;
                    //case "btnPrometio": this.textBox1.Text = QPrometio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QPrometio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnNeptunio": this.textBox1.Text = QNeptunio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QNeptunio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnCobalto": this.textBox1.Text = QCobalto.Pregunta; this.radioButton1.Text = QCobalto.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnRodio": this.textBox1.Text = QRodio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = this.QRodio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnIridio": this.textBox1.Text = QIridio.Pregunta; this.radioButton1.Text = QIridio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnMeitnerio": this.textBox1.Text = QMeitnerio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QMeitnerio.Respuesta; break;
                    //case "btnSamario": this.textBox1.Text = QSamario.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QSamario.Respuesta; break;
                    //case "btnPlutonio": this.textBox1.Text = QPlutonio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QPlutonio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnNiquel": this.textBox1.Text = QNiquel.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QNiquel.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnPaladio": this.textBox1.Text = QPaladio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QPaladio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnPlatino": this.textBox1.Text = QPlatino.Pregunta; this.radioButton1.Text = QPlatino.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnDarmstatio": this.textBox1.Text = QDarmstatio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QDarmstatio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnEuropio": this.textBox1.Text = QEuropio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QEuropio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnAmericio": this.textBox1.Text = QAmericio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QAmericio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnCobre": this.textBox1.Text = QCobre.Pregunta; this.radioButton1.Text = QCobre.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnPlata": this.textBox1.Text = QPlata.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QPlata.Respuesta; break;
                    //case "btnOro": this.textBox1.Text = QOro.Pregunta; this.radioButton1.Text = QOro.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnRoentgenio": this.textBox1.Text = QRoentgenio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QRoentgenio.Respuesta; break;
                    //case "btnGadolinio": this.textBox1.Text = QGadolinio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QGadolinio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnCurio": this.textBox1.Text = QCurio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QCurio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnZinc": this.textBox1.Text = QZinc.Pregunta; this.radioButton1.Text = QZinc.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnCadmio": this.textBox1.Text = QCadmio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QCadmio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnMercurio": this.textBox1.Text = QMercurio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QMercurio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnCopernicio": this.textBox1.Text = QCopernicio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QCopernicio.Respuesta; break;
                    //case "btnTerbio": this.textBox1.Text = QTerbio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QTerbio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnBerkelio": this.textBox1.Text = QBerkelio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QBerkelio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnBoro": this.textBox1.Text = QBoro.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QBoro.Respuesta; break;
                    //case "btnAluminio": this.textBox1.Text = QAluminio.Pregunta; this.radioButton1.Text = QAluminio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnGalio": this.textBox1.Text = QGalio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QGalio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnIndio": this.textBox1.Text = QIndio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QIndio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnTalio": this.textBox1.Text = QTalio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QTalio.Respuesta; break;
                    //case "btnNihonio": this.textBox1.Text = QNihonio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QNihonio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnDisprosio": this.textBox1.Text = QDisprosio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QDisprosio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnCalifornio": this.textBox1.Text = QCalifornio.Pregunta; this.radioButton1.Text = QCalifornio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnCarbono": this.textBox1.Text = QCarbono.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QCarbono.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnSilicio": this.textBox1.Text = QSilicio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QSilicio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnGermanio": this.textBox1.Text = QGermanio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QGermanio.Respuesta; break;
                    //case "btnEstaño": this.textBox1.Text = QEstaño.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QEstaño.Respuesta; break;
                    //case "btnPlomo": this.textBox1.Text = QPlomo.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QPlomo.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnFlerovio": this.textBox1.Text = QFlerovio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QFlerovio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnHolmio": this.textBox1.Text = QHolmio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QHolmio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnEinstenio": this.textBox1.Text = QEinstenio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QEinstenio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnNitrogeno": this.textBox1.Text = QNitrogeno.Pregunta; this.radioButton1.Text = QNitrogeno.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnFosforo": this.textBox1.Text = QFosforo.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QFosforo.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnArsenico": this.textBox1.Text = QArsenico.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QArsenico.Respuesta; break;
                    //case "btnAntimonio": this.textBox1.Text = QAntimonio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QAntimonio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnBismuto": this.textBox1.Text = QBismuto.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QBismuto.Respuesta; this.radioButton3.Text = "      "; this.radioButton4.Text = "      "; break;
                    //case "btnMoscovio": this.textBox1.Text = QMoscovio.Pregunta; this.radioButton1.Text = QMoscovio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnErbio": this.textBox1.Text = QErbio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QErbio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnFermio": this.textBox1.Text = QFermio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QFermio.Respuesta; break;
                    //case "btnOxigeno": this.textBox1.Text = QOxigeno.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QOxigeno.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnAzufre": this.textBox1.Text = QAzufre.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QAzufre.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnSelenio": this.textBox1.Text = QSelenio.Pregunta; this.radioButton1.Text = QSelenio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnTelurio": this.textBox1.Text = QTelurio.Pregunta; this.radioButton1.Text = QTelurio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnPolonio": this.textBox1.Text = QPolonio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QPolonio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnLivermorio": this.textBox1.Text = QLivermorio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QLivermorio.Respuesta; break;
                    //case "btnTulio": this.textBox1.Text = QTulio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QTulio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnMendelevio": this.textBox1.Text = QMendelevio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QMendelevio.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnFluor": this.textBox1.Text = QFluor.Pregunta; this.radioButton1.Text = QFluor.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnCloro": this.textBox1.Text = QCloro.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QCloro.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnBromo": this.textBox1.Text = QBromo.Pregunta; this.radioButton1.Text = QBromo.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnYodo": this.textBox1.Text = QYodo.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QYodo.Respuesta; break;
                    //case "btnAstato": this.textBox1.Text = QAstato.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QAstato.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnTeneso": this.textBox1.Text = QTeneso.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QTeneso.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnIterbio": this.textBox1.Text = QIterbio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QIterbio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnNobelio": this.textBox1.Text = QNobelio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QNobelio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnHelio": this.textBox1.Text = QHelio.Pregunta; this.radioButton1.Text = QHelio.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnNeon": this.textBox1.Text = QNeon.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QNeon.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnArgon": this.textBox1.Text = QArgon.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = QArgon.Respuesta; break;
                    //case "btnKripton": this.textBox1.Text = QKripton.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QKripton.Respuesta; this.radioButton4.Text = "		"; break;
                    //case "btnXenon": this.textBox1.Text = QXenon.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QXenon.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnRadon": this.textBox1.Text = QRadon.Pregunta; this.radioButton1.Text = QRadon.Respuesta; this.radioButton2.Text = "		"; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnOganeson": this.textBox1.Text = QOganeson.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QOganeson.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnLutecio": this.textBox1.Text = QLutecio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = QLutecio.Respuesta; this.radioButton3.Text = "		"; this.radioButton4.Text = "		"; break;
                    //case "btnLawrencio": this.textBox1.Text = QLawrencio.Pregunta; this.radioButton1.Text = "		"; this.radioButton2.Text = "		"; this.radioButton3.Text = QLawrencio.Respuesta; this.radioButton4.Text = "		"; break;
                    #endregion
            }

        }
        public void crearPreguntas()
        {
            QotrosNoMetales = new Question { Elemento = "Otros No Metales", Pregunta = "Son elementos químicos que no son buenos conductores de la corriente eléctrica y el \ncalor. Son muy débiles, por lo que no se pueden ni estirar ni convertir en una lámina", Respuesta = "Otros No Metales" };
            QAlcalinos = new Question { Elemento = "Alcalinos", Pregunta = "Son metales brillantes, blandos, altamente reactivos a temperatura y presión estándar odos se\npueden cortar fácilmente con un cuchillo debido a su suavidad, exponiendo una superficie brillante que se empaña rápidamente en el aire debido a la oxidación\npor la humedad atmosférica y el oxígeno ", Respuesta = "Alcalinos" };
            QAlcalinoterreo = new Question { Elemento = "Alcalinoterreo", Pregunta = "Son más duros que los metales alcalinos, tienen brillo y son buenos conductores eléctricos; menos reactivos que los alcalinos, buenos agentes reductores y forman compuestos iónicos. Todos ellos tienen dos electrones en su capa más externa", Respuesta = "Alcalinoterreo" };
            QMetalesTransicion = new Question { Elemento = "Metales de Transicion", Pregunta = "Son elementos  estables por sí mismos sin necesidad de una reacción con otro elemento.  Son maleables y dúctiles, conducen calor y electricidad, y forman iones positivos. Sin embargo, estos elementos son más electronegativos y tienen más probabilidades de formar compuestos covalentes", Respuesta = "Metales de Transición" };
            QOtrosMetales = new Question { Elemento = "Otros Metales", Pregunta = "Son elementos  que tienden a ser blandos y a tener puntos de fusión bajos. Casi todos los elementos son metales típicos, de elevada dureza, con puntos de fusión y ebullición altos, buenos conductores tanto del calor como de la electricidad.", Respuesta = "Otros Metales" };
            QLantanidos = new Question { Elemento = "Lantanidos", Pregunta = "Son un grupo de elementos que forman parte del periodo 6 de la tabla periódica de los elementos. Estos elementos son llamados «tierras raras» debido a que se encuentran en forma de óxidos, y también, junto con los actínidos, forman los «elementos de transición interna».", Respuesta = "Lantánidos" };
            QActinidos = new Question { Elemento = "Actinidos", Pregunta = "Son un grupo de elementos que forman parte del periodo 7 de la tabla periódica. Estos elementos, junto con los lantánidos, son llamados elementos de transición interna. Tienen un alto número atómico, y algunos como el Uranio se encuentran en ínfimas cantidades en la naturaleza y tienen tiempos de vida media cortos; todos sus isótopos son radiactivos.", Respuesta = "Actínidos" };
            QMetaloide = new Question { Elemento = "Metaloide", Pregunta = "Se caracterizan por presentar un comportamiento intermedio entre los metales y los no metales, compartiendo características de ambos. Son mejores conductores de calor y de electricidad que los no metales, pero no tanto como los metales", Respuesta = "Metaloide" };
            QHalogenos = new Question { Elemento = "Halogenos", Pregunta = "Los seis elementos químicos que se encuentran en el grupo 17 (VIIA) de la tabla periódica. Presentan comportamientos químicos semejantes, como el hecho de formar sales de sodio (Na) muy parecidas. Fueron utilizados principalmente en forma de sales, que los antiguos fenicios y griegos empleaban como método de preservación de la comida (salmuera).", Respuesta = "Halogenos" };
            QGasesNobles = new Question { Elemento = "Gases Nobles", Pregunta = "Son un grupo de elementos químicos con propiedades muy similares: por ejemplo, bajo condiciones normales, son gases monoatómicos inodoros, incoloros y presentan una reactividad química muy baja. Presentan una serie de características en común: la más importante su bajísimo grado de reactividad, es decir, su poca capacidad para formar compuestos y estructurar moléculas complejas", Respuesta = "Gases Nobles" };


            #region elementos
            //QHidrogeno = new Question { Elemento = "Hidrogeno", Pregunta = "Este elemento constituye más del 90 % de los átomos del universo y en 1776 se reconoció\n por primera vez como una sustancia diferente. En la Tierra, se encuentra frecuentemente \ncombinado con oxígeno en forma de agua y también está presente en las plantas, el petróleo, el carbón y otra materia orgánica", Respuesta = "Hidrogeno" };
            //QLitio = new Question { Elemento = "Litio", Pregunta = "Este elemento se descubrió en 1817 y es el más ligero de todos los metales.\nTambién se utiliza como material para el polo positivo de las baterías y en vidrios y cerámicas.", Respuesta = "Litio" };
            //QSodio = new Question { Elemento = "Sodio", Pregunta = "Es bastante abundante en el Sol y las estrellas, es el cuarto elemento más abundante en la Tierra\nSe encuentra en la SAL.Éste elemento es importante en las industrias del papel, el vidrio, el jabón, los\n textiles, el petróleo, los productos químicos y la metalúrgica.", Respuesta = "Sodio" };
            //QPotasio = new Question { Elemento = "Potasio", Pregunta = "Este elemento se usa en gran medida  en fertilizantes debido a que es esencial\n para el crecimiento de las plantas.", Respuesta = "Potasio" };
            //QRubidio = new Question { Elemento = "Rubidio", Pregunta = "", Respuesta = "Rubidio" };
            //QCesio = new Question { Elemento = "Cesio", Pregunta = "", Respuesta = "Cesio" };
            //QFrancio = new Question { Elemento = "Francio", Pregunta = "", Respuesta = "Francio" };
            //QBerilio = new Question { Elemento = "Berilio", Pregunta = " Se descubrió como un óxido en berilos y esmeraldas en 1798.\nEste elemento  se utiliza como un material estructural para aeronaves de alta velocidad,\n naves espaciales, satélites y mísiles.", Respuesta = "Berilio" };
            //QMagnesio = new Question { Elemento = "Magnesio", Pregunta = "Es el octavo elemento más abundante en la corteza terrestre\nSe utiliza para flashes fotográficos, luces de bengala, pirotecnia y bombas incendiarias", Respuesta = "Magnesio" };
            //QCalcio = new Question { Elemento = "Calcio", Pregunta = "Este metal alcalinotérreo es el quinto más abundante de la corteza\n terrestre y se encuentra en hojas, huesos, dientes y conchas.", Respuesta = "Calcio" };
            //QEstroncio = new Question { Elemento = "Estroncio", Pregunta = "", Respuesta = "Estroncio" };
            //QBario = new Question { Elemento = "Bario", Pregunta = "", Respuesta = "Bario" };
            //QRadio = new Question { Elemento = "Radio", Pregunta = "", Respuesta = "Radio" };
            //QEscandio = new Question { Elemento = "Escandio", Pregunta = "Es mucho más abundante en el Sol y ciertas estrellas que en la Tierra.\nSe usa en las lámparas de alta intensidad.", Respuesta = "Escandio" };
            //QItrio = new Question { Elemento = "Itrio", Pregunta = "", Respuesta = "Itrio" };
            //QLantanidos = new Question { Elemento = "Lantanidos", Pregunta = "", Respuesta = "Lantanidos" };
            //QActinidos = new Question { Elemento = "Actinidos", Pregunta = "", Respuesta = "Actinidos" };
            //QTitanio = new Question { Elemento = "Titanio", Pregunta = "Es un metal brillante de color blanco, al combinarse con el hierro y aluminio\nse  puede usar en la fabricacion de prótesis médicas e implantes ortopédicos, instrumentos e \nimplantes dentales, aparatos deportivos, joyería o teléfonos móviles", Respuesta = "Titanio" };
            //QCirconio = new Question { Elemento = "Circonio", Pregunta = "", Respuesta = "Circonio" };
            //QHafnio = new Question { Elemento = "Hafnio", Pregunta = "", Respuesta = "Hafnio" };
            //QRutherfordio = new Question { Elemento = "Rutherfordio", Pregunta = "", Respuesta = "Rutherfordio" };
            //QLantano = new Question { Elemento = "Lantano", Pregunta = "", Respuesta = "Lantano" };
            //QActinio = new Question { Elemento = "Actinio", Pregunta = "", Respuesta = "Actinio" };
            //QVanadio = new Question { Elemento = "Vanadio", Pregunta = "Se utiliza habitualmente en aplicaciones nucleares y para la fabricación de aceros.\nSe puede utilizar para proteger el acero contra la oxidación y la corrosión", Respuesta = "Vanadio" };
            //QNiobio = new Question { Elemento = "Niobio", Pregunta = "", Respuesta = "Niobio" };
            //QTantalo = new Question { Elemento = "Tantalo", Pregunta = "", Respuesta = "Tantalo" };
            //QDubnio = new Question { Elemento = "Dubnio", Pregunta = "", Respuesta = "Dubnio" };
            //QCerio = new Question { Elemento = "Cerio", Pregunta = "", Respuesta = "Cerio" };
            //QTorio = new Question { Elemento = "Torio", Pregunta = "", Respuesta = "Torio" };
            //QCromo = new Question { Elemento = "Cromo", Pregunta = "Se utiliza para endurecer el acero, fabricar acero inoxidable , entre otros.\nEstá presente en algunos alimentos, pero es tóxico en exceso.", Respuesta = "Cromo" };
            //QMolibdeno = new Question { Elemento = "Molibdeno", Pregunta = "", Respuesta = "Molibdeno" };
            //QWolframio = new Question { Elemento = "Wolframio", Pregunta = "", Respuesta = "Wolframio" };
            //QSeaborgio = new Question { Elemento = "Seaborgio", Pregunta = "", Respuesta = "Seaborgio" };
            //QPraseodimio = new Question { Elemento = "Praseodimio", Pregunta = "", Respuesta = "Praseodimio" };
            //QProtactinio = new Question { Elemento = "Protactinio", Pregunta = "", Respuesta = "Protactinio" };
            //QManganesio = new Question { Elemento = "Manganeso", Pregunta = "Tienen colores diferentes y se utilizan industrialmente como tintes", Respuesta = "Manganeso" };
            //QTecnecio = new Question { Elemento = "Tecnecio", Pregunta = "", Respuesta = "Tecnecio" };
            //QRenio = new Question { Elemento = "Renio", Pregunta = "", Respuesta = "Renio" };
            //QBohrio = new Question { Elemento = "Bohrio", Pregunta = "", Respuesta = "Bohrio" };
            //QNeodimio = new Question { Elemento = "Neodimio", Pregunta = "", Respuesta = "Neodimio" };
            //QUranio = new Question { Elemento = "Uranio", Pregunta = "", Respuesta = "Uranio" };
            //QHierro = new Question { Elemento = "Hierro", Pregunta = "El núcleo de la Tierra está formado principalmente por este elemento\n. Es extremadamente duro y denso.", Respuesta = "Hierro" };
            //QRutenio = new Question { Elemento = "Rutenio", Pregunta = "", Respuesta = "Rutenio" };
            //QOsmio = new Question { Elemento = "Osmio", Pregunta = "", Respuesta = "Osmio" };
            //QHasio = new Question { Elemento = "Hasio", Pregunta = "", Respuesta = "Hasio" };
            //QPrometio = new Question { Elemento = "Prometio", Pregunta = "", Respuesta = "Prometio" };
            //QNeptunio = new Question { Elemento = "Neptunio", Pregunta = "", Respuesta = "Neptunio" };
            //QCobalto = new Question { Elemento = "Cobalto", Pregunta = "Es un metal fragil  y se usa en la fabricacionen turbinas de aviación y generadores de turbinas de gas.\nTambien se han utilizado durante siglos para obtener un color azul intenso del vidrio, los esmaltes y cerámicas.", Respuesta = "Cobalto" };
            //QRodio = new Question { Elemento = "Rodio", Pregunta = "", Respuesta = "Rodio" };
            //QIridio = new Question { Elemento = "Iridio", Pregunta = "", Respuesta = "Iridio" };
            //QMeitnerio = new Question { Elemento = "Meitnerio", Pregunta = "", Respuesta = "Meitnerio" };
            //QSamario = new Question { Elemento = "Samario", Pregunta = "", Respuesta = "Samario" };
            //QPlutonio = new Question { Elemento = "Plutonio", Pregunta = "", Respuesta = "Plutonio" };
            //QNiquel = new Question { Elemento = "Niquel", Pregunta = "Se utiliza para fabricar acero inoxidable, también en cerámica, fabricación de imanes\n y en baterías recargables.", Respuesta = "Niquel" };
            //QPaladio = new Question { Elemento = "Paladio", Pregunta = "", Respuesta = "Paladio" };
            //QPlatino = new Question { Elemento = "Platino", Pregunta = "", Respuesta = "Platino" };
            //QDarmstatio = new Question { Elemento = "Darmstatio", Pregunta = "", Respuesta = "Darmstatio" };
            //QEuropio = new Question { Elemento = "Europio", Pregunta = "", Respuesta = "Europio" };
            //QAmericio = new Question { Elemento = "Americio", Pregunta = "", Respuesta = "Americio" };
            //QCobre = new Question { Elemento = "Cobre", Pregunta = "Es un metal rojizo y es un buen conductor de calor y electricidad.\nEl mayor uso que se le da es en la industria eléctrica, tambien se utilizan en las monedas", Respuesta = "Cobre" };
            //QPlata = new Question { Elemento = "Plata", Pregunta = "", Respuesta = "Plata" };
            //QOro = new Question { Elemento = "Oro", Pregunta = "", Respuesta = "Oro" };
            //QRoentgenio = new Question { Elemento = "Roentgenio", Pregunta = "", Respuesta = "Roentgenio" };
            //QGadolinio = new Question { Elemento = "Gadolinio", Pregunta = "", Respuesta = "Gadolinio" };
            //QCurio = new Question { Elemento = "Curio", Pregunta = "", Respuesta = "Curio" };
            //QZinc = new Question { Elemento = "Zinc", Pregunta = "Se utilizaba para fabricar latón,  las láminas de dicho material se emplean en \nconstrucciones de viviendas improvisadas o criaderos de animales.", Respuesta = "Zinc" };
            //QCadmio = new Question { Elemento = "Cadmio", Pregunta = "", Respuesta = "Cadmio" };
            //QMercurio = new Question { Elemento = "Mercurio", Pregunta = "", Respuesta = "Mercurio" };
            //QCopernicio = new Question { Elemento = "Copernicio", Pregunta = "", Respuesta = "Copernicio" };
            //QTerbio = new Question { Elemento = "Terbio", Pregunta = "", Respuesta = "Terbio" };
            //QBerkelio = new Question { Elemento = "Berkelio", Pregunta = "", Respuesta = "Berkelio" };
            //QBoro = new Question { Elemento = "Boro", Pregunta = "Este elemento se utiliza en los fuegos artificiales haciendo\nque sus destellos sean de color verde.\nSe utiliza para la fabricación de fibra de vidrio aislante.", Respuesta = "Boro" };
            //QAluminio = new Question { Elemento = "Aluminio", Pregunta = "Es el metal más abundante en la corteza terrestre (8,1 %) y se encuentra en la arcilla y otros muchos\n minerales comunes.", Respuesta = "Aluminio" };
            //QGalio = new Question { Elemento = "Galio", Pregunta = "", Respuesta = "Galio" };
            //QIndio = new Question { Elemento = "Indio", Pregunta = "", Respuesta = "Indio" };
            //QTalio = new Question { Elemento = "Talio", Pregunta = "", Respuesta = "Talio" };
            //QNihonio = new Question { Elemento = "Nihonio", Pregunta = "", Respuesta = "Nihonio" };
            //QDisprosio = new Question { Elemento = "Disprosio", Pregunta = "", Respuesta = "Disprosio" };
            //QCalifornio = new Question { Elemento = "Californio", Pregunta = "", Respuesta = "Californio" };
            //QCarbono = new Question { Elemento = "Carbono", Pregunta = "Está ampliamente distribuido en la naturaleza y se encuentra dentro de las estrellas,\ncometas y en las atmósferas de la mayoría de planetas.", Respuesta = "Carbono" };
            //QSilicio = new Question { Elemento = "Silicio", Pregunta = "", Respuesta = "Silicio" };
            //QGermanio = new Question { Elemento = "Germanio", Pregunta = "", Respuesta = "Germanio" };
            //QEstaño = new Question { Elemento = "Estaño", Pregunta = "", Respuesta = "Estaño" };
            //QPlomo = new Question { Elemento = "Plomo", Pregunta = "", Respuesta = "Plomo" };
            //QFlerovio = new Question { Elemento = "Flerovio", Pregunta = "", Respuesta = "Flerovio" };
            //QHolmio = new Question { Elemento = "Holmio", Pregunta = "", Respuesta = "Holmio" };
            //QEinstenio = new Question { Elemento = "Einstenio", Pregunta = "", Respuesta = "Einstenio" };
            //QNitrogeno = new Question { Elemento = "Nitrogeno", Pregunta = "Se encuentra en los materiales biológicos de todos los seres vivos. \nSus compuestos se encuentran en materiales orgánicos y fertilizantes, venenos y explosivos.", Respuesta = "Nitrogeno" };
            //QFosforo = new Question { Elemento = "Fosforo", Pregunta = "Son importantes para la agricultura y los cultivos como componentes de fertilizantes. \nTambién se usan para producir cristales especiales, porcelana fina y levadura química", Respuesta = "Fósforo" };
            //QArsenico = new Question { Elemento = "Arsenico", Pregunta = "", Respuesta = "Arsenico" };
            //QAntimonio = new Question { Elemento = "Antimonio", Pregunta = "", Respuesta = "Antimonio" };
            //QBismuto = new Question { Elemento = "Bismuto", Pregunta = "", Respuesta = "Bismuto" };
            //QMoscovio = new Question { Elemento = "Moscovio", Pregunta = "", Respuesta = "Moscovio" };
            //QErbio = new Question { Elemento = "Erbio", Pregunta = "", Respuesta = "Erbio" };
            //QFermio = new Question { Elemento = "Fermio", Pregunta = "", Respuesta = "Fermio" };
            //QOxigeno = new Question { Elemento = "Oxigeno", Pregunta = "Es un componente de cientos de miles de compuestos orgánicos y se combina fácilmente con la\nmayoría de elementos. Si dividieramos el cuerpo en 3 partes una de ellas estaria formada unicamente de éste\n elemento.", Respuesta = "Oxigeno" };
            //QAzufre = new Question { Elemento = "Azufre", Pregunta = "Es esencial para la vida y es un componente menor de grasas, líquidos y secreciones corporales \ny minerales óseos. Se encuentra de forma natural en las proximidades de los Volcanes y aguas termales", Respuesta = "Azufre" };
            //QSelenio = new Question { Elemento = "Selenio", Pregunta = "", Respuesta = "Selenio" };
            //QTelurio = new Question { Elemento = "Telurio", Pregunta = "", Respuesta = "Telurio" };
            //QPolonio = new Question { Elemento = "Polonio", Pregunta = "", Respuesta = "Polonio" };
            //QLivermorio = new Question { Elemento = "Livermorio", Pregunta = "", Respuesta = "Livermorio" };
            //QTulio = new Question { Elemento = "Tulio", Pregunta = "", Respuesta = "Tulio" };
            //QMendelevio = new Question { Elemento = "Mendelevio", Pregunta = "", Respuesta = "Mendelevio" };
            //QFluor = new Question { Elemento = "Fluor", Pregunta = "Sus compuestos ayudan a producir uranio  y más de 100 productos químicos comerciales y \nplásticos para altas temperaturas. Al combinarlo en agua potable se ha utilizado para ayudar a evitar las \ncaries dentales.", Respuesta = "Fluor" };
            //QCloro = new Question { Elemento = "Cloro", Pregunta = "Se usa para producir agua potable segura y para la fabricación de productos de papel, \ntintes, textiles, productos de petróleo, medicamentos, antisépticos, insecticidas, alimentos,  pinturas, \nplásticos y muchos otros producto", Respuesta = "Cloro" };
            //QBromo = new Question { Elemento = "Bromo", Pregunta = "", Respuesta = "Bromo" };
            //QYodo = new Question { Elemento = "Yodo", Pregunta = "", Respuesta = "Yodo" };
            //QAstato = new Question { Elemento = "Astato", Pregunta = "", Respuesta = "Astato" };
            //QTeneso = new Question { Elemento = "Teneso", Pregunta = "", Respuesta = "Teneso" };
            //QIterbio = new Question { Elemento = "Iterbio", Pregunta = "", Respuesta = "Iterbio" };
            //QNobelio = new Question { Elemento = "Nobelio", Pregunta = "", Respuesta = "Nobelio" };
            //QHelio = new Question { Elemento = "Helio", Pregunta = "El primer indicio de este elemento se detectó durante el eclipse solar de 1868. \nEs el segundo elemento más abundante y se puede extraer a partir de gas natural. ", Respuesta = "Helio" };
            //QNeon = new Question { Elemento = "Neon", Pregunta = "Es un elemento poco frecuente y gaseoso. Se usa con mayor frecuencia en\navisos publicitarios, también se usa con el helio para fabricar láseres gaseosos.", Respuesta = "Neón" };
            //QArgon = new Question { Elemento = "Argon", Pregunta = "Este elemento se usa para bombillas de lámparas incandescentes y fluorescentes.", Respuesta = "Argón" };
            //QKripton = new Question { Elemento = "Kripton", Pregunta = "", Respuesta = "Kripton" };
            //QXenon = new Question { Elemento = "Xenon", Pregunta = "", Respuesta = "Xenon" };
            //QRadon = new Question { Elemento = "Radon", Pregunta = "", Respuesta = "Radon" };
            //QOganeson = new Question { Elemento = "Oganeson", Pregunta = "", Respuesta = "Oganeson" };
            //QLutecio = new Question { Elemento = "Lutecio", Pregunta = "", Respuesta = "Lutecio" };
            //QLawrencio = new Question { Elemento = "Lawrencio", Pregunta = "", Respuesta = "Lawrencio" };
            #endregion

        }

        public void button1_Click(object sender, EventArgs e)
        {
            switch (Elemento)
            {
                case "OtrosNoMetales": if (radioButton1.Checked && String.Equals(radioButton1.Text, QotrosNoMetales.Respuesta)) Respuesta.respuesta = true; break;
                case "Alcalinos": if (radioButton3.Checked && String.Equals(radioButton3.Text, QAlcalinos.Respuesta)) Respuesta.respuesta = true; break;
                case "Alcalinoterreo": if (radioButton3.Checked && String.Equals(radioButton3.Text, QAlcalinoterreo.Respuesta)) Respuesta.respuesta = true; break;
                case "MetalesTransicion": if (radioButton2.Checked && String.Equals(radioButton2.Text, QMetalesTransicion.Respuesta)) Respuesta.respuesta = true; break;
                case "OtrosMetales": if (radioButton3.Checked && String.Equals(radioButton3.Text, QOtrosMetales.Respuesta)) Respuesta.respuesta = true; break;
                case "Lantanidos": if (radioButton4.Checked && String.Equals(radioButton4.Text, QLantanidos.Respuesta)) Respuesta.respuesta = true; break;
                case "Actinidos": if (radioButton1.Checked && String.Equals(radioButton1.Text, QActinidos.Respuesta)) Respuesta.respuesta = true; break;
                case "Metaloide": if (radioButton2.Checked && String.Equals(radioButton2.Text, QMetaloide.Respuesta)) Respuesta.respuesta = true; break;
                case "Halogenos": if (radioButton4.Checked && String.Equals(radioButton4.Text, QHalogenos.Respuesta)) Respuesta.respuesta = true; break;
                case "GasesNobles": if (radioButton1.Checked && String.Equals(radioButton1.Text, QGasesNobles.Respuesta)) Respuesta.respuesta = true; break;

                #region elementos
                //case "btnHidrogeno": if (radioButton1.Checked && String.Equals(radioButton1.Text, QHidrogeno.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnLitio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QLitio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnSodio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QSodio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnPotasio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QPotasio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnRubidio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QRubidio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCesio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QCesio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnFrancio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QFrancio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnBerilio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QBerilio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnMagnesio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QMagnesio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCalcio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QCalcio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnEstroncio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QEstroncio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnBario": if (radioButton3.Checked && String.Equals(radioButton3.Text, QBario.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnRadio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QRadio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnEscandio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QEscandio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnItrio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QItrio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnLantanidos": if (radioButton3.Checked && String.Equals(radioButton3.Text, QLantanidos.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnActinidos": if (radioButton4.Checked && String.Equals(radioButton4.Text, QActinidos.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnTitanio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QTitanio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCirconio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QCirconio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnHafnio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QHafnio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnRutherfordio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QRutherfordio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnLantano": if (radioButton4.Checked && String.Equals(radioButton4.Text, QLantano.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnActinio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QActinio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnVanadio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QVanadio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnNiobio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QNiobio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnTantalo": if (radioButton3.Checked && String.Equals(radioButton3.Text, QTantalo.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnDubnio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QDubnio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCerio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QCerio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnTorio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QTorio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCromo": if (radioButton3.Checked && String.Equals(radioButton3.Text, QCromo.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnMolibdeno": if (radioButton2.Checked && String.Equals(radioButton2.Text, QMolibdeno.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnWolframio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QWolframio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnSeaborgio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QSeaborgio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnPraseodimio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QPraseodimio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnProtactinio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QProtactinio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnManganesio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QManganesio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnTecnecio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QTecnecio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnRenio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QRenio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnBohrio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QBohrio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnNeodimio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QNeodimio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnUranio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QUranio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnHierro": if (radioButton4.Checked && String.Equals(radioButton4.Text, QHierro.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnRutenio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QRutenio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnOsmio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QOsmio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnHasio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QHasio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnPrometio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QPrometio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnNeptunio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QNeptunio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCobalto": if (radioButton1.Checked && String.Equals(radioButton1.Text, QCobalto.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnRodio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QRodio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnIridio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QIridio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnMeitnerio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QMeitnerio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnSamario": if (radioButton4.Checked && String.Equals(radioButton4.Text, QSamario.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnPlutonio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QPlutonio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnNiquel": if (radioButton2.Checked && String.Equals(radioButton2.Text, QNiquel.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnPaladio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QPaladio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnPlatino": if (radioButton1.Checked && String.Equals(radioButton1.Text, QPlatino.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnDarmstatio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QDarmstatio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnEuropio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QEuropio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnAmericio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QAmericio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCobre": if (radioButton1.Checked && String.Equals(radioButton1.Text, QCobre.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnPlata": if (radioButton4.Checked && String.Equals(radioButton4.Text, QPlata.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnOro": if (radioButton1.Checked && String.Equals(radioButton1.Text, QOro.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnRoentgenio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QRoentgenio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnGadolinio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QGadolinio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCurio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QCurio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnZinc": if (radioButton1.Checked && String.Equals(radioButton1.Text, QZinc.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCadmio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QCadmio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnMercurio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QMercurio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCopernicio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QCopernicio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnTerbio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QTerbio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnBerkelio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QBerkelio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnBoro": if (radioButton4.Checked && String.Equals(radioButton4.Text, QBoro.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnAluminio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QAluminio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnGalio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QGalio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnIndio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QIndio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnTalio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QTalio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnNihonio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QNihonio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnDisprosio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QDisprosio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCalifornio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QCalifornio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCarbono": if (radioButton2.Checked && String.Equals(radioButton2.Text, QCarbono.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnSilicio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QSilicio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnGermanio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QGermanio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnEstaño": if (radioButton4.Checked && String.Equals(radioButton4.Text, QEstaño.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnPlomo": if (radioButton3.Checked && String.Equals(radioButton3.Text, QPlomo.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnFlerovio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QFlerovio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnHolmio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QHolmio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnEinstenio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QEinstenio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnNitrogeno": if (radioButton1.Checked && String.Equals(radioButton1.Text, QNitrogeno.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnFosforo": if (radioButton3.Checked && String.Equals(radioButton3.Text, QFosforo.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnArsenico": if (radioButton4.Checked && String.Equals(radioButton4.Text, QArsenico.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnAntimonio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QAntimonio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnBismuto": if (radioButton2.Checked && String.Equals(radioButton2.Text, QBismuto.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnMoscovio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QMoscovio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnErbio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QErbio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnFermio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QFermio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnOxigeno": if (radioButton3.Checked && String.Equals(radioButton3.Text, QOxigeno.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnAzufre": if (radioButton2.Checked && String.Equals(radioButton2.Text, QAzufre.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnSelenio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QSelenio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnTelurio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QTelurio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnPolonio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QPolonio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnLivermorio": if (radioButton4.Checked && String.Equals(radioButton4.Text, QLivermorio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnTulio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QTulio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnMendelevio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QMendelevio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnFluor": if (radioButton1.Checked && String.Equals(radioButton1.Text, QFluor.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnCloro": if (radioButton2.Checked && String.Equals(radioButton2.Text, QCloro.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnBromo": if (radioButton1.Checked && String.Equals(radioButton1.Text, QBromo.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnYodo": if (radioButton4.Checked && String.Equals(radioButton4.Text, QYodo.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnAstato": if (radioButton2.Checked && String.Equals(radioButton2.Text, QAstato.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnTeneso": if (radioButton3.Checked && String.Equals(radioButton3.Text, QTeneso.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnIterbio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QIterbio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnNobelio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QNobelio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnHelio": if (radioButton1.Checked && String.Equals(radioButton1.Text, QHelio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnNeon": if (radioButton3.Checked && String.Equals(radioButton3.Text, QNeon.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnArgon": if (radioButton4.Checked && String.Equals(radioButton4.Text, QArgon.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnKripton": if (radioButton3.Checked && String.Equals(radioButton3.Text, QKripton.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnXenon": if (radioButton2.Checked && String.Equals(radioButton2.Text, QXenon.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnRadon": if (radioButton1.Checked && String.Equals(radioButton1.Text, QRadon.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnOganeson": if (radioButton2.Checked && String.Equals(radioButton2.Text, QOganeson.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnLutecio": if (radioButton2.Checked && String.Equals(radioButton2.Text, QLutecio.Respuesta)) Respuesta.respuesta = true; break;
                //case "btnLawrencio": if (radioButton3.Checked && String.Equals(radioButton3.Text, QLawrencio.Respuesta)) Respuesta.respuesta = true; break;
                #endregion
                default: Respuesta.respuesta = false; break;
            }
            validarRespuesta();
        }

        public void validarRespuesta()
        {
            if (!Respuesta.respuesta)
            {
                MessageBox.Show("Respuesta Incorrecta", "Error", MessageBoxButtons.OK/*, MessageBoxIcon.Error*/);
            }
            else
            {
                MessageBox.Show("Respuesta Correcta", "Correcto!", MessageBoxButtons.OK/*, MessageBoxIcon.Information*/);
                this.Close();
            }

        }

        private void Cuestionario_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
                button1_Click(sender, e);
            if (e.KeyCode == Keys.Escape)
                this.Close();
        }
    }
}
